print("Hey, I am learning git. And this is my first file I am committing and pushing to github")
print('This is arshad , committing for second time')
print('This is arshd , commiting for third ')
print('commiting for third time')
print('commting for forth time')
print("committing for fifth time")
